repository: jk1mm/moneyball

output: web

topnav_title: moneyball

site_title: moneyball

github_editme_path: jk1mm/moneyball/tree/release

host: 127.0.0.1

port: 4000

exclude:
  - .idea/
  - .gitignore
  - vendor

feedback_subject_line: moneyball

feedback_email: joshkim47@gmail.com

feedback_disable: false

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: demo_sidebar
      topnav: topnav

sidebars:
- demo_sidebar
- mydoc_sidebar

url: "http://jk1mm.github.io"
baseurl: "/moneyball"

social:
  - title: github
    url: http://github.com/jk1mm
  - title: linkedin
    url: https://www.linkedin.com/in/1joshkim/

github: [metadata]
