source "https://rubygems.org"

# to publish on github page
gem 'github-pages', group: :jekyll_plugins

# to publish without github page
#gem "jekyll"

# security fix
gem "kramdown", ">= 2.3.0"
gem "rubyzip", ">= 1.3.0"
gem "nokogiri", ">= 1.11.0"
